receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch: {}

exporters:
  # Debug exporter (writes telemetry to the Collector logs)
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  # Export traces to Jaeger via OTLP
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Export traces to Tempo via OTLP
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Expose metrics on an internal endpoint for Prometheus to scrape
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Export logs to Loki via OTLP HTTP
  otlphttp/loki:
    endpoint: "loki:3100/loki/api/v1/push"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger, otlp/tempo]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]

    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp/loki]
